# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diseño.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(760, 558)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_superior = QtWidgets.QFrame(self.frame)
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 42))
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_superior.setStyleSheet("QFrame {\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:#000000ff;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:rgb(53, 53, 79);\n"
"border-radius:20px;\n"
"}")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.frame_superior)
        self.label.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: white;")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(339, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.bt_cerrar2 = QtWidgets.QPushButton(self.frame_superior)
        self.bt_cerrar2.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_cerrar2.setStyleSheet("")
        self.bt_cerrar2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagenes/minimo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_cerrar2.setIcon(icon)
        self.bt_cerrar2.setIconSize(QtCore.QSize(30, 30))
        self.bt_cerrar2.setObjectName("bt_cerrar2")
        self.horizontalLayout.addWidget(self.bt_cerrar2)
        self.bt_minimizar = QtWidgets.QPushButton(self.frame_superior)
        self.bt_minimizar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_minimizar.setStyleSheet("")
        self.bt_minimizar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imagenes/minimizar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_minimizar.setIcon(icon1)
        self.bt_minimizar.setIconSize(QtCore.QSize(30, 30))
        self.bt_minimizar.setObjectName("bt_minimizar")
        self.horizontalLayout.addWidget(self.bt_minimizar)
        self.bt_maximixar = QtWidgets.QPushButton(self.frame_superior)
        self.bt_maximixar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_maximixar.setStyleSheet("")
        self.bt_maximixar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("imagenes/maximizar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_maximixar.setIcon(icon2)
        self.bt_maximixar.setIconSize(QtCore.QSize(30, 30))
        self.bt_maximixar.setObjectName("bt_maximixar")
        self.horizontalLayout.addWidget(self.bt_maximixar)
        self.bt_cerrar = QtWidgets.QPushButton(self.frame_superior)
        self.bt_cerrar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_cerrar.setStyleSheet("")
        self.bt_cerrar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("imagenes/cerrrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_cerrar.setIcon(icon3)
        self.bt_cerrar.setIconSize(QtCore.QSize(30, 30))
        self.bt_cerrar.setObjectName("bt_cerrar")
        self.horizontalLayout.addWidget(self.bt_cerrar)
        self.verticalLayout_2.addWidget(self.frame_superior)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setStyleSheet("QFrame{\n"
"background-color: rgb(55, 53, 79);\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 87 12pt \"Arial Black\";\n"
"background-color: #000000ff;\n"
"color: rgb(20, 200, 220);\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: black;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_paginas = QtWidgets.QFrame(self.frame_4)
        self.frame_paginas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_paginas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_paginas.setObjectName("frame_paginas")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_paginas)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.toolBox = QtWidgets.QToolBox(self.frame_paginas)
        self.toolBox.setStyleSheet("QToolBox::tab{\n"
"background-color: rgb(14, 140, 180);\n"
"border-radius: 5px;\n"
"color: rgb(255, 255, 255);\n"
"font: 95 10pt \"Arial Black\";\n"
"}\n"
"\n"
"QToolBoox::tab::selected{\n"
"background-color: rgb(20, 200, 220);\n"
"font: 75 12pt \"MS Shell Dlg 2\"; \n"
"color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 87 12pt \"Arial Black\";\n"
"background-color: #000000ff;\n"
"color: white;\n"
"border-radius: 5px;\n"
"border: 1px solid #14C8DC;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba( 255, 255, 255, 25% );\n"
"}\n"
"")
        self.toolBox.setObjectName("toolBox")
        self.Cadena = QtWidgets.QWidget()
        self.Cadena.setGeometry(QtCore.QRect(0, 0, 716, 360))
        self.Cadena.setObjectName("Cadena")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Cadena)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.boton_abrir = QtWidgets.QPushButton(self.Cadena)
        self.boton_abrir.setObjectName("boton_abrir")
        self.verticalLayout_4.addWidget(self.boton_abrir)
        self.boton_mostrar = QtWidgets.QPushButton(self.Cadena)
        self.boton_mostrar.setObjectName("boton_mostrar")
        self.verticalLayout_4.addWidget(self.boton_mostrar)
        self.frame_3 = QtWidgets.QFrame(self.Cadena)
        self.frame_3.setStyleSheet("QWidget {\n"
"background-color: rgba( 255, 255, 255, 35%);\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"background-color: rgb(14, 140, 180);\n"
"padding: 2px;\n"
"\n"
"border: 1px solid #fffff8; \n"
"font-size: 14pt;\n"
"}\n"
"\n"
"ATableWidget{\n"
"gridline-color: #aa00ff; \n"
"font-size: 12pt; \n"
"color: rgb(255, 255, 255);\n"
"font: 95 10pt \"Arial Black\";\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section{\n"
"background-color: #646464;\n"
"border: 1px solid #ff000;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_5.addWidget(self.tableWidget)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.toolBox.addItem(self.Cadena, "")
        self.TodasCombinacion = QtWidgets.QWidget()
        self.TodasCombinacion.setGeometry(QtCore.QRect(0, 0, 716, 360))
        self.TodasCombinacion.setObjectName("TodasCombinacion")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.TodasCombinacion)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_12 = QtWidgets.QPushButton(self.TodasCombinacion)
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_8.addWidget(self.pushButton_12)
        self.boton_abrir_2 = QtWidgets.QPushButton(self.TodasCombinacion)
        self.boton_abrir_2.setObjectName("boton_abrir_2")
        self.verticalLayout_8.addWidget(self.boton_abrir_2)
        self.frame_5 = QtWidgets.QFrame(self.TodasCombinacion)
        self.frame_5.setStyleSheet("QWidget {\n"
"background-color: rgba( 255, 255, 255, 35%);\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"background-color: rgb(14, 140, 180);\n"
"padding: 2px;\n"
"\n"
"border: 1px solid #fffff8; \n"
"font-size: 14pt;\n"
"}\n"
"\n"
"ATableWidget{\n"
"gridline-color: #aa00ff; \n"
"font-size: 12pt; \n"
"color: rgb(255, 255, 255);\n"
"font: 95 10pt \"Arial Black\";\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section{\n"
"background-color: #646464;\n"
"border: 1px solid #ff000;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame_5)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.verticalLayout_7.addWidget(self.tableWidget_2)
        self.verticalLayout_8.addWidget(self.frame_5)
        self.toolBox.addItem(self.TodasCombinacion, "")
        self.RangosCombinacion = QtWidgets.QWidget()
        self.RangosCombinacion.setGeometry(QtCore.QRect(0, 0, 716, 360))
        self.RangosCombinacion.setObjectName("RangosCombinacion")
        self.spinBox = QtWidgets.QSpinBox(self.RangosCombinacion)
        self.spinBox.setGeometry(QtCore.QRect(80, 90, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.RangosCombinacion)
        self.spinBox_2.setGeometry(QtCore.QRect(160, 90, 42, 22))
        self.spinBox_2.setObjectName("spinBox_2")
        self.toolBox.addItem(self.RangosCombinacion, "")
        self.TuplasCombinacion = QtWidgets.QWidget()
        self.TuplasCombinacion.setGeometry(QtCore.QRect(0, 0, 716, 360))
        self.TuplasCombinacion.setObjectName("TuplasCombinacion")
        self.toolBox.addItem(self.TuplasCombinacion, "")
        self.verticalLayout_6.addWidget(self.toolBox)
        self.verticalLayout_3.addWidget(self.frame_paginas)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(1)
        self.bt_cerrar.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "EDICION DE CADENAS"))
        self.boton_abrir.setText(_translate("MainWindow", "Abrir Archivo"))
        self.boton_mostrar.setText(_translate("MainWindow", "Mostrar Datos"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Cadena), _translate("MainWindow", "Importar Tabla de Cadenas"))
        self.pushButton_12.setText(_translate("MainWindow", "Hacer Combinaciones"))
        self.boton_abrir_2.setText(_translate("MainWindow", "Mostrar Combinaciones"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.TodasCombinacion), _translate("MainWindow", "Todas las combinaciones"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.RangosCombinacion), _translate("MainWindow", "Combinaciones por Rangos"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.TuplasCombinacion), _translate("MainWindow", "Combinaciones por Tuplas"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
